package no04com.thiru.constructor0;
/*
CONSTRUCTOR
============ 
	TO INITIALIZE THE OBJECT

RULES
=====
	CONSTRUCTOR NAME CLASS NAME SHOULD BE SAME
	NO RETURN TYPES OF CONSTRUCTORS 

1)DEFAULT CONSTRUCTOR
2)NO-ARGUMENT CONSTRUCTOR OR 0-PARAM CONSTRUCTOR
3)PARAMETERAISED CONSTRUCTOR


1)DEFAULT CONSTRUCTOR (AUTOGENERATED CONSTRUCTOR)
	Person () {//we don’t write code}
	Compiler   	==>	 	creates 			 ==>	a default constructor where there is no parameterized constructor (or) no-argument constructor constructor in a class. 
	Compiler 	==>		does not create 	 ==>	a default constructor when there is a parameterized constructor (or) no-argument constructor found.


2)NO-ARGUMENT CONSTRUCTOR (USER DEFINED CONSTRUCTOR)
	Person () {//we have to write code}
	To initialize the object with default values

3)PARAMETERAISED CONSTRUCTOR (USER DEFINED CONSTRUCTOR)
	To initialize the object with given set of values



 */
public class Constructor {


}
