package com.thiru.abstractclass;

public interface Laptop {
	
	
	//ABSTRACT CLASS: ABSTRACT CLASS IS CLASS WHICH IS HAVING ABSTRACT METHODS AND 
	//IT IS DEFINED WITH THE ABSTRACT KEY WORD
	
	//WE CAN'T PROVIDE FULLY IMPLEMENTATION WE CAN PROVIDE PARTAIL IMPLEMENTATION
	//THIS IS A LAYER BEWTEEN CLASS(FULLY IMPLEMENTED METHODS) AND INTERFACE(ABSTRACT METHODS)
	
	
	public void copy();
	public void paste();
	public void cut();
	public void keyBoard();
	



}
